services:

  tomcat:
    image: tomcat
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./target/carshare-app:/usr/local/tomcat/webapps/carshare-app/
    ports:
      - "8090:8080"
    restart: unless-stopped