services:

  tomcat:
    image: tomcat
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./target/carshare-app:/usr/local/tomcat/webapps/carshare-app/
    ports:
      - "8090:8080"
    networks:
      - carshare
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carshare
      MYSQL_USER: tomcat
      MYSQL_PASSWORD: tomcat
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - carshare
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_PORT: 3306
      PMA_HOST: mysql
      PMA_USER: tomcat
      PMA_PASSWORD: tomcat
    ports:
      - "8091:80"
    networks:
      - carshare
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql-data:

networks:
    carshare:
        driver: bridge